name: mock_trade
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  english_words: ^4.0.0
  web_socket_channel: ^3.0.1
  flutter_dotenv: ^5.2.1
  dio: ^5.7.0
  intl: ^0.19.0
  auto_route: ^9.2.2
  webview_flutter: ^4.10.0
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  firebase_ui_auth: ^1.16.0
  firebase_ui_oauth_google: ^1.4.0
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^9.0.0

flutter:
  uses-material-design: true
