stages:
  - build
  - deploy

build_frontend:
  stage: build
  tags:
    - docker
  image: ghcr.io/cirruslabs/flutter:latest
  script:
    - cd frontend
    - flutter pub get
    - flutter build web --release --dart-define-from-file=$FRONTEND_ENV
  artifacts:
    paths:
      - frontend/build/web/
  when: manual

build_backend:
  stage: build
  tags:
    - docker
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - cd backend
    - echo "$CI_DEPLOY_PASSWORD" | docker login $CI_REGISTRY -u $CI_DEPLOY_USER --password-stdin
    - docker buildx create --driver docker-container --use
    - docker buildx build --platform linux/amd64,linux/arm64 -t $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_NAME --push .
  when: manual


pages:
  stage: deploy
  dependencies:
    - build_frontend
  script:
    - mkdir public
    - cp -R frontend/build/web/* public/
  artifacts:
    paths:
      - public
  when: manual

deploy_backend:
  stage: deploy
  tags:
    - prod-deploy
  script:
    - echo "$CI_DEPLOY_PASSWORD" | docker login $CI_REGISTRY -u $CI_DEPLOY_USER --password-stdin
    - docker pull $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_NAME
    - docker stop backend || true
    - docker rm backend || true
    - docker run -d 
      --name backend 
      -p 80:3000 
      --env-file $BACKEND_ENV 
      -e GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS
      --volume $GOOGLE_APPLICATION_CREDENTIALS:$GOOGLE_APPLICATION_CREDENTIALS
      $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_NAME
  when: manual