variables:
  GOOGLE_CREDENTIAL_PATH: "./gcloud-service-key.json"

stages:
  - build
  - deploy

build_backend:
  stage: build
  tags:
    - docker
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  script:
    - cd backend
    - cp $GOOGLE_APPLICATION_CREDENTIALS $GOOGLE_CREDENTIAL_PATH
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/backend"
      --dockerfile "${CI_PROJECT_DIR}/backend/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/backend:${CI_COMMIT_TAG}"
  when: manual

deploy_backend:
  stage: deploy
  tags:
    - prod-deploy
  script:
    - echo "$CI_DEPLOY_PASSWORD" | docker login $CI_REGISTRY -u $CI_DEPLOY_USER --password-stdin
    - docker pull $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_NAME
    - docker stop backend || true
    - docker rm backend || true
    - docker run -d --name backend -p 80:3000 --env-file $BACKEND_ENV -e GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_CREDENTIAL_PATH $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_NAME
  when: manual